[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "netlify/functions" 